name: Documentation
on:
  pull_request:
  release:
    types: [created]

jobs:
  Documentation:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.2
      - name: Build SDK
        run: |
          dotnet build dropbox-sdk-dotnet/Dropbox.Api
      - name: Build Documentation
        run: |
          dotnet restore doc/StoneDocs.shfbproj
          msbuild doc/StoneDocs.shfbproj # WinForms refuse to work with .NET 5.0
          tar -cvzf doc/Help.tar.gz doc/Help
      - name: Upload Documentation
        uses: actions/upload-artifact@v2
        with:
          path: doc/Help.tar.gz
      - name: Push Documentation
        uses: JamesIves/github-pages-deploy-action@releases/v3
        if: github.event_name == 'release'
        with:
          ACCESS_TOKEN: ${{ secrets.GH_PAGES_PUBLISH_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: doc/Help # The folder the action should deploy.
